export const PERSIST_DEBOUNCE_MS = 3000
export const CHECKPOINT_INTERVAL = 200
export const WS_IDLE_TIMEOUT_S = 30
export const WS_MAX_PAYLOAD = 6 * 1024 * 1024
export const WS_POLICY_CLOSE_CODE = 1008

export const MAX_FILE_BYTES = 500 * 1024 * 1024
export const MAX_PEER_FILE_BYTES = 1024 * 1024 * 1024
export const MAX_PEER_FILE_COUNT = 5
export const MAX_TEXT_BYTES = 1 * 1024 * 1024
export const MAX_DRAWING_BYTES = 2 * 1024 * 1024
export const MAX_PAD_PATH_BYTES = 512
export const MAX_PAD_PATH_SEGMENTS = 12
export const MAX_PAD_PATH_SEGMENT_BYTES = MAX_PAD_PATH_BYTES
export const MAX_RELATED_PADS = 100
export const MAX_ROOM_CLIENTS = 32
export const MAX_AWARENESS_BYTES = 16 * 1024
export const MAX_FILE_ID_BYTES = 128
export const MAX_FILE_NAME_BYTES = 180
export const MAX_FILE_MIME_BYTES = 120
export const MAX_FILE_REJECT_REASON_BYTES = 180
export const MAX_FILE_SIGNAL_BYTES = 16 * 1024
export const MAX_PEER_NAME_BYTES = 80
export const MAX_WS_MESSAGE_BYTES_PER_WINDOW = 2 * 1024 * 1024
export const MAX_WS_MESSAGES_PER_WINDOW = 2400
export const MAX_WS_UPGRADES_PER_WINDOW = 60
export const MAX_WS_ACTIVE_PER_IP = 64
export const MAX_PAD_WRITES_PER_WINDOW = 1200
export const MAX_WS_BUFFERED_BYTES = 512 * 1024

export const Y_TEXT_KEY = 'text'
export const Y_DRAWING_ELEMENTS_KEY = 'elements'
